const List<Map<String, dynamic>> surasInfo = [
  {'name': 'الفاتحة', 'count': 7, 'number': 1},
  {'name': 'البقرة', 'count': 286, 'number': 2},
  {'name': 'آل عمران', 'count': 200, 'number': 3},
  {'name': 'النساء', 'count': 176, 'number': 4},
  {'name': 'المائدة', 'count': 120, 'number': 5},
  {'name': 'الأنعام', 'count': 165, 'number': 6},
  {'name': 'الأعراف', 'count': 206, 'number': 7},
  {'name': 'الأنفال', 'count': 75, 'number': 8},
  {'name': 'التوبة', 'count': 129, 'number': 9},
  {'name': 'يونس', 'count': 109, 'number': 10},
  {'name': 'هود', 'count': 123, 'number': 11},
  {'name': 'يوسف', 'count': 111, 'number': 12},
  {'name': 'الرعد', 'count': 43, 'number': 13},
  {'name': 'إبراهيم', 'count': 52, 'number': 14},
  {'name': 'الحجر', 'count': 99, 'number': 15},
  {'name': 'النحل', 'count': 128, 'number': 16},
  {'name': 'الإسراء', 'count': 111, 'number': 17},
  {'name': 'الكهف', 'count': 110, 'number': 18},
  {'name': 'مريم', 'count': 98, 'number': 19},
  {'name': 'طه', 'count': 135, 'number': 20},
  {'name': 'الأنبياء', 'count': 112, 'number': 21},
  {'name': 'الحج', 'count': 78, 'number': 22},
  {'name': 'المؤمنون', 'count': 118, 'number': 23},
  {'name': 'النور', 'count': 64, 'number': 24},
  {'name': 'الفرقان', 'count': 77, 'number': 25},
  {'name': 'الشعراء', 'count': 227, 'number': 26},
  {'name': 'النمل', 'count': 93, 'number': 27},
  {'name': 'القصص', 'count': 88, 'number': 28},
  {'name': 'العنكبوت', 'count': 69, 'number': 29},
  {'name': 'الروم', 'count': 60, 'number': 30},
  {'name': 'لقمان', 'count': 34, 'number': 31},
  {'name': 'السجدة', 'count': 30, 'number': 32},
  {'name': 'الأحزاب', 'count': 73, 'number': 33},
  {'name': 'سبأ', 'count': 54, 'number': 34},
  {'name': 'فاطر', 'count': 45, 'number': 35},
  {'name': 'يس', 'count': 83, 'number': 36},
  {'name': 'الصافات', 'count': 182, 'number': 37},
  {'name': 'ص', 'count': 88, 'number': 38},
  {'name': 'الزمر', 'count': 75, 'number': 39},
  {'name': 'غافر', 'count': 85, 'number': 40},
  {'name': 'فصلت', 'count': 54, 'number': 41},
  {'name': 'الشورى', 'count': 53, 'number': 42},
  {'name': 'الزخرف', 'count': 89, 'number': 43},
  {'name': 'الدخان', 'count': 59, 'number': 44},
  {'name': 'الجاثية', 'count': 37, 'number': 45},
  {'name': 'الأحقاف', 'count': 35, 'number': 46},
  {'name': 'محمد', 'count': 38, 'number': 47},
  {'name': 'الفتح', 'count': 29, 'number': 48},
  {'name': 'الحجرات', 'count': 18, 'number': 49},
  {'name': 'ق', 'count': 45, 'number': 50},
  {'name': 'الذاريات', 'count': 60, 'number': 51},
  {'name': 'الطور', 'count': 49, 'number': 52},
  {'name': 'النجم', 'count': 62, 'number': 53},
  {'name': 'القمر', 'count': 55, 'number': 54},
  {'name': 'الرحمن', 'count': 78, 'number': 55},
  {'name': 'الواقعة', 'count': 96, 'number': 56},
  {'name': 'الحديد', 'count': 29, 'number': 57},
  {'name': 'المجادلة', 'count': 22, 'number': 58},
  {'name': 'الحشر', 'count': 24, 'number': 59},
  {'name': 'الممتحنة', 'count': 13, 'number': 60},
  {'name': 'الصف', 'count': 14, 'number': 61},
  {'name': 'الجمعة', 'count': 11, 'number': 62},
  {'name': 'المنافقون', 'count': 11, 'number': 63},
  {'name': 'التغابن', 'count': 18, 'number': 64},
  {'name': 'الطلاق', 'count': 12, 'number': 65},
  {'name': 'التحريم', 'count': 12, 'number': 66},
  {'name': 'الملك', 'count': 30, 'number': 67},
  {'name': 'القلم', 'count': 52, 'number': 68},
  {'name': 'الحاقة', 'count': 52, 'number': 69},
  {'name': 'المعارج', 'count': 44, 'number': 70},
  {'name': 'نوح', 'count': 28, 'number': 71},
  {'name': 'الجن', 'count': 28, 'number': 72},
  {'name': 'المزمل', 'count': 20, 'number': 73},
  {'name': 'المدثر', 'count': 56, 'number': 74},
  {'name': 'القيامة', 'count': 40, 'number': 75},
  {'name': 'الإنسان', 'count': 31, 'number': 76},
  {'name': 'المرسلات', 'count': 50, 'number': 77},
  {'name': 'النبأ', 'count': 40, 'number': 78},
  {'name': 'النازعات', 'count': 46, 'number': 79},
  {'name': 'عبس', 'count': 42, 'number': 80},
  {'name': 'التكوير', 'count': 29, 'number': 81},
  {'name': 'الانفطار', 'count': 19, 'number': 82},
  {'name': 'المطففين', 'count': 36, 'number': 83},
  {'name': 'الانشقاق', 'count': 25, 'number': 84},
  {'name': 'البروج', 'count': 22, 'number': 85},
  {'name': 'الطارق', 'count': 17, 'number': 86},
  {'name': 'الأعلى', 'count': 19, 'number': 87},
  {'name': 'الغاشية', 'count': 26, 'number': 88},
  {'name': 'الفجر', 'count': 30, 'number': 89},
  {'name': 'البلد', 'count': 20, 'number': 90},
  {'name': 'الشمس', 'count': 15, 'number': 91},
  {'name': 'الليل', 'count': 21, 'number': 92},
  {'name': 'الضحى', 'count': 11, 'number': 93},
  {'name': 'الشرح', 'count': 8, 'number': 94},
  {'name': 'التين', 'count': 8, 'number': 95},
  {'name': 'العلق', 'count': 19, 'number': 96},
  {'name': 'القدر', 'count': 5, 'number': 97},
  {'name': 'البينة', 'count': 8, 'number': 98},
  {'name': 'الزلزلة', 'count': 8, 'number': 99},
  {'name': 'العاديات', 'count': 11, 'number': 100},
  {'name': 'القارعة', 'count': 11, 'number': 101},
  {'name': 'التكاثر', 'count': 8, 'number': 102},
  {'name': 'العصر', 'count': 3, 'number': 103},
  {'name': 'الهمزة', 'count': 9, 'number': 104},
  {'name': 'الفيل', 'count': 5, 'number': 105},
  {'name': 'قريش', 'count': 4, 'number': 106},
  {'name': 'الماعون', 'count': 7, 'number': 107},
  {'name': 'الكوثر', 'count': 3, 'number': 108},
  {'name': 'الكافرون', 'count': 6, 'number': 109},
  {'name': 'النصر', 'count': 3, 'number': 110},
  {'name': 'المسد', 'count': 5, 'number': 111},
  {'name': 'الإخلاص', 'count': 4, 'number': 112},
  {'name': 'الفلق', 'count': 5, 'number': 113},
  {'name': 'الناس', 'count': 6, 'number': 114},
];

const List<Map<String, dynamic>> juzInfo = [
  {'juz': 1, 'ayahCount': 148, 'firstAyah': 'الم'},
  {
    'juz': 2,
    'ayahCount': 111,
    'firstAyah':
        'سَيَقُولُ السُّفَهَاءُ مِنَ النَّاسِ مَا وَلَّاهُمْ عَنْ قِبْلَتِهِمُ الَّتِي كَانُوا عَلَيْهَا',
  },
  {
    'juz': 3,
    'ayahCount': 126,
    'firstAyah': 'تِلْكَ الرُّسُلُ فَضَّلْنَا بَعْضَهُمْ عَلَىٰ بَعْضٍ',
  },
  {
    'juz': 4,
    'ayahCount': 131,
    'firstAyah':
        'يَا أَيُّهَا النَّاسُ اتَّقُوا رَبَّكُمُ الَّذِي خَلَقَكُمْ مِنْ نَفْسٍ وَاحِدَةٍ',
  },
  {
    'juz': 5,
    'ayahCount': 124,
    'firstAyah':
        'وَالْمُحْصَنَاتُ مِنَ النِّسَاءِ إِلَّا مَا مَلَكَتْ أَيْمَانُكُمْ',
  },
  {
    'juz': 6,
    'ayahCount': 110,
    'firstAyah':
        'يَا أَيُّهَا الَّذِينَ آمَنُوا لَا تَتَّخِذُوا الْيَهُودَ وَالنَّصَارَىٰ أَوْلِيَاءَ',
  },
  {
    'juz': 7,
    'ayahCount': 149,
    'firstAyah':
        'وَإِذَا سَمِعُوا مَا أُنزِلَ إِلَى الرَّسُولِ تَرَىٰ أَعْيُنَهُمْ تَفِيضُ مِنَ الدَّمْعِ',
  },
  {
    'juz': 8,
    'ayahCount': 142,
    'firstAyah': 'وَلَوْ أَنَّهُمْ أَقَامُوا التَّوْرَاةَ وَالْإِنجِيلَ',
  },
  {'juz': 9, 'ayahCount': 159, 'firstAyah': 'قَدْ أَفْلَحَ مَنْ تَزَكَّىٰ'},
  {
    'juz': 10,
    'ayahCount': 127,
    'firstAyah': 'وَاعْلَمُوا أَنَّمَا غَنِمْتُمْ مِنْ شَيْءٍ',
  },
  {
    'juz': 11,
    'ayahCount': 151,
    'firstAyah': 'يَا أَيُّهَا النَّبِيُّ اتَّقِ اللَّهَ',
  },
  {
    'juz': 12,
    'ayahCount': 170,
    'firstAyah': 'وَقَالَ الْمَلِكُ ائْتُونِي بِهِ',
  },
  {'juz': 13, 'ayahCount': 154, 'firstAyah': 'وَمَا أُبَرِّئُ نَفْسِي'},
  {
    'juz': 14,
    'ayahCount': 227,
    'firstAyah': 'رُبَمَا يَوَدُّ الَّذِينَ كَفَرُوا',
  },
  {
    'juz': 15,
    'ayahCount': 185,
    'firstAyah': 'سُبْحَانَ الَّذِي أَسْرَىٰ بِعَبْدِهِ',
  },
  {'juz': 16, 'ayahCount': 269, 'firstAyah': 'قَدْ أَفْلَحَ الْمُؤْمِنُونَ'},
  {
    'juz': 17,
    'ayahCount': 190,
    'firstAyah': 'وَقَالَ الَّذِينَ كَفَرُوا لِلَّذِينَ آمَنُوا',
  },
  {
    'juz': 18,
    'ayahCount': 202,
    'firstAyah':
        'الْحَمْدُ لِلَّهِ الَّذِي أَنْزَلَ عَلَىٰ عَبْدِهِ الْكِتَابَ',
  },
  {
    'juz': 19,
    'ayahCount': 339,
    'firstAyah': 'وَقَالَ الَّذِينَ كَفَرُوا إِنْ هَٰذَا إِلَّا إِفْكٌ',
  },
  {
    'juz': 20,
    'ayahCount': 171,
    'firstAyah': 'أَمَّنْ خَلَقَ السَّمَاوَاتِ وَالْأَرْضَ',
  },
  {'juz': 21, 'ayahCount': 178, 'firstAyah': 'اتْلُ مَا أُوحِيَ إِلَيْكَ'},
  {
    'juz': 22,
    'ayahCount': 169,
    'firstAyah': 'وَمَنْ يَقْنُتْ مِنْكُنَّ لِلَّهِ وَرَسُولِهِ',
  },
  {
    'juz': 23,
    'ayahCount': 357,
    'firstAyah': 'وَمَا أَنْزَلْنَا عَلَىٰ قَوْمِهِ مِنْ بَعْدِهِ مِنْ جُنْدٍ',
  },
  {
    'juz': 24,
    'ayahCount': 175,
    'firstAyah': 'فَمَنْ أَظْلَمُ مِمَّنْ كَذَبَ عَلَى اللَّهِ',
  },
  {
    'juz': 25,
    'ayahCount': 246,
    'firstAyah': 'إِلَيْهِ يُرَدُّ عِلْمُ السَّاعَةِ',
  },
  {
    'juz': 26,
    'ayahCount': 195,
    'firstAyah': 'قَالَ فَمَا خَطْبُكُمْ أَيُّهَا الْمُرْسَلُونَ',
  },
  {
    'juz': 27,
    'ayahCount': 399,
    'firstAyah': 'قَالَ فَمَا بَالُ الْقُرُونِ الْأُولَىٰ',
  },
  {
    'juz': 28,
    'ayahCount': 137,
    'firstAyah': 'قَدْ سَمِعَ اللَّهُ قَوْلَ الَّتِي تُجَادِلُكَ',
  },
  {
    'juz': 29,
    'ayahCount': 431,
    'firstAyah': 'تَبَارَكَ الَّذِي بِيَدِهِ الْمُلْكُ',
  },
  {'juz': 30, 'ayahCount': 564, 'firstAyah': 'عَمَّ يَتَسَاءَلُونَ'},
];
